### ISSUE TITLE
README Information

### ISSUE THREAD

**Issue by RegisGraptin** [RegisGraptin/ChainLink-constellation-2023#1]
I think we need to centralize all the project information to avoid disparity, especially if we have on the telegram, on the github or to another google doc...

Thus, I suggest we centralize all the information in one place. I suggest we use github and write on the README that can be use to present our project, the code organization... And if too much information, we can then move and create a documentation for this github project.

Also, I think we need to provide in the README information as deployed addresses/contract. As those two information, I think it is relevant to put it in the README.
```
Here is one minted NFT transaction: 0x740155b6c0c16106b55c2af95df375d21a0840567ae6b3f40ecbc02f437dc65f 
And here is the Tokenbound account address for an instance: 0xf0F34fE82844011d5752184588c8913f1c937F84
```

Finally, I think we can keep basic command to run the project (front) and also have the comment if we want to deployed on hardhat locally the soul bound token.

**Comment by Riki0923** [comment]
.env file

NEXT_PUBLIC_WALLET_ADDRESS="yours"
NEXT_PUBLIC_PRIVATE_KEY="yours"
NEXT_PUBLIC_ALCHEMY_GOERLI_URL="https://eth-goerli.g.alchemy.com/v2/tIAej_5Kj4-1AJoFWxuIsrwOtHMp1JPK"
NEXT_PUBLIC_ALCHEMY_GOERLI_API_KEY="tIAej_5Kj4-1AJoFWxuIsrwOtHMp1JPK"
NEXT_PUBLIC_GIFT_NFT="0x26eccA91c44beF3d2Fe4eCA31b13Ac88D8efE56D"
NEXT_PUBLIC_ERC6551ACOUNT_ADDRESS="0x37E34Dce222c2bB9e01ca0EA5f73c2f4CF3Bdb0e"
NEXT_PUBLIC_ERC6551REGISTRY_ADDRESS="0xB0EC946845E4798684A557deeD6009d9617A2803"
NEXT_PUBLIC_CCIP_CONTRACT_ADDRESS_SEPOLIA="0x0467D708a14d2E20AD0572D414dEb4B297522d35"
NEXT_PUBLIC_CCIP_CONTRACT_ADDRESS_AVALANCHE=""
