### ISSUE TITLE
Project description - features

### ISSUE THREAD

**Issue by RegisGraptin** [RegisGraptin/ChainLink-constellation-2023#2]
I think it should be interesting to defined/present the project from a global vision. 
Then, move to the functionalities and defined what we need to do and which technology we need to use, to give us a first glance of the work to accomplish. We also need to decomposed them as small as possible to see what are the different steps we need to do, but I think it can come in a second time.
And maybe we need to prioritize them, to concentrate our effort on the most important first.

@aloksahay did you already start working on this? Else, I would suggest to start writing about it here. And eventually defined the features that we talk about. Maybe we can create a first list for that. And when ready, we can create an issue that defined what is the scope of the features and attribute it to someone. Can be a cumbersome process but as we are in remote, not working at the same time and have other projects in mind, I think it can be interesting to have the information easily allowing anyone to work at his own pace.

**Comment by RegisGraptin** [comment]
An example of what we could build. I set some idea, but we can talk about it in another comments. Also, this comment can be edited:

# [Project Name]
[Description]

## Features

- [x] Initialize the repository (hardhat)
- [ ] Create a gift to a person
     - [ ] Creation of the gift
          - [x] Create the Solidity contract - Soul bound token
          - [ ] Implement in the UI the creation of this contract
          - [ ] Share by a link to other people ?
     - [ ] Send the gift at the specific date
          - [ ] Chainlink automation?
          - [ ] Notification on the UI?
- [ ] Generate a gift card message
     - [ ] Select a LLM to generate a message
     - [ ] Use Chainlink function to call the API
     - [ ] Integrated it in the UI
 - [ ] CCIP implementation ( Avalanche + Goerli / Polygon )

**Comment by Riki0923** [comment]
NEXT_PUBLIC_ALCHEMY_SEPOLIA_URL="https://eth-sepolia.g.alchemy.com/v2/3UgB5gXO0xUSqr6IReBPB7ULztScB-tw"
NEXT_PUBLIC_ALCHEMY_SEPOLIA_API_KEY="3UgB5gXO0xUSqr6IReBPB7ULztScB-tw"
NEXT_PUBLIC_GIFT_NFT="0xDE463BbF511fd4cDC634003B22755a57a58C9a70"
NEXT_PUBLIC_ERC6551ACOUNT_ADDRESS="0x15D8e9b40e818324D28431fbdd4703e8FcB9780c"
NEXT_PUBLIC_ERC6551REGISTRY_ADDRESS="0xe566b65Bc13604Eca2482D2432Ad6C75bf8eAA09"
NEXT_PUBLIC_CCIP_CONTRACT_ADDRESS_SEPOLIA="0x0467D708a14d2E20AD0572D414dEb4B297522d35"
NEXT_PUBLIC_CCIP_CONTRACT_ADDRESS_AVALANCHE="0x09cb994F331d251d725B748E75CF4748F2dA6E1f"
NEXT_PUBLIC_TBD_ACCOUNT="0x1ACCa0ae6Aed1032625bD38B06c78EBBa31958C7"
