### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by RegisGraptin** [RegisGraptin/ChainLink-constellation-2023#3]
I think we should split the contract and the front in two folders to avoid dependencies errors and it will facilitate future merge as it will separate those two. As we do not use scaffold-eth, I think we should have at the root two folders:
- `front/`: dedicated for the frontend part
- `contract`: dedicated for the smart contract development.

This will avoid too much files at the root. 
Do not know what you think about it @Riki0923 ?

**Comment by Riki0923** [comment]
I aggree going with this way Regis.
